config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    member do
      put :change
    end
  end
  devise_for :users
  root 'pages#home'

  get 'about' => 'pages#about'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user

  validates :user_id, presence: true
  validates :content, presence: true

  auto_html_for :content do
    html_escape
    youtube(width: '80%', height: 250 )
    link target: '_blank', rel: 'nofollow'
    simple_format
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if current_user
      redirect_to tasks_path
    end
  end

  def about
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy, :change]

  # GET /tasks
  # GET /tasks.json
  def index
    @to_do = current_user.tasks.where(state: 'to_do')
    @doing = current_user.tasks.where(state: 'doing')
    @done = current_user.tasks.where(state: 'done')
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def change
    @task.update_attributes(state: params[:state])
    respond_to do |format|
      format.html { redirect_to tasks_path, notice: 'Task updated'}
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "<i class='fa fa-check-square-o'></i> PMT".html_safe, root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
            <li><%= link_to "Board", tasks_path %></li>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete%></li>
        <% else %>
            <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectManagmentTool</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<%= render "layouts/header" %>
  <%= yield %>
</body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h1>About Us</h1>
  <p>This is the page about the people who create the app</p>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="jumbotron">
    <h1><i class="fa fa-check-square-o"></i> Project managment tool</h1>
    <p>This is a ToDo list like a kanban board</p>
    <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-primary btn-lg' %>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
    <% if f.error_notification.nil? %>
    <% else %>
        <div class="container">
          <div class="alert alert-danger" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <p id="notice"><%= f.error_notification %></p>
          </div>
        </div>
    <% end %>
    <%= f.error_notification %>

    <div class="form-group">
      <%= f.input :content, required: true, label: false, autofocus:true, class: 'form-control', placeholder: 'Content' %>
    </div>
    <div class="form-group">
      <%= f.input :state %>
    </div>

    <div class="form-group">
      <%= f.button :submit , class: 'btn btn-primary btn-block' %>
    </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="col-md-12">
  <div class="row">
    <p style="width: 100%">
      <%= raw(task.content_html) %>
    </p>
    <p>
      <%= task.created_at.to_formatted_s(:short) %>
    </p>
  </div>
  <div class="row">
    <% if task.state == "doing" %>
        <%= link_to "<i class='fa fa-arrow-left'></i>".html_safe, change_task_path(task, state: "to_do"), method: :put, class: 'btn btn-primary' %>
    <% end %>
    <% if task.state == "done" %>
        <%= link_to "<i class='fa fa-arrow-left'></i>".html_safe, change_task_path(task, state: "doing"), method: :put, class: 'btn btn-primary' %>
    <% end %>
    <%= link_to "<i class='fa fa-eye'></i>".html_safe, task ,class: 'btn btn-primary' %>
    <%= link_to "<i class='fa fa-pencil'></i>".html_safe, edit_task_path(task), class: 'btn btn-primary' %>
    <%= link_to "<i class='fa fa-trash'></i>".html_safe, task, method: :delete, class: 'btn btn-primary' ,data: { confirm: 'Are you sure?' } %>
    <% if task.state == "doing" %>
        <%= link_to "<i class='fa fa-arrow-right'></i>".html_safe, change_task_path(task, state: "done"), method: :put, class: 'btn btn-primary' %>
    <% end %>
    <% if task.state == "to_do" %>
        <%= link_to "<i class='fa fa-arrow-right'></i>".html_safe, change_task_path(task, state: "doing"), method: :put, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading text-center">
      <h1>Editing Task</h1>
    </div>
    <div class="panel-body">
      <%= render 'form' %>
      <%= link_to 'Show', @task, class: 'btn btn-primary btn-block' %>
      <%= link_to 'Back', tasks_path, class: 'btn btn-primary btn-block' %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<% if notice.nil? %>
<% else %>
    <div class="container">
      <div class="alert alert-info" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <p id="notice"><%= notice %></p>
      </div>
    </div>
<% end %>
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h4>Board</h4>

    </div>
    <div class="panel-body">
      <div class="container" style="margin-bottom: 1em">
        <%= link_to "<i class='fa fa-plus'></i>".html_safe, new_task_path, class: 'btn btn-primary btn-block' %>
      </div>
      <div class="col-md-4">
        <div class="panel panel-info">
          <div class="panel-heading text-center">
            <h5>To Do</h5>
          </div>
          <div class="panel-body">
            <%= render @to_do %>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="panel panel-info">
          <div class="panel-heading text-center">
            <h5>Doing</h5>
          </div>
          <div class="panel-body">
            <%= render @doing %>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="panel panel-info">
          <div class="panel-heading text-center">
            <h5>Done</h5>
          </div>
          <div class="panel-body">
            <%= render @done %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading text-center">
      <h1>New Task</h1>
    </div>
    <div class="panel-body" >
        <%= render 'form' %>
        <%= link_to 'Back', tasks_path, class: 'btn btn-primary btn-block' %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <% if notice.nil? %>
  <% else %>
      <div class="container">
        <div class="alert alert-info" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <p id="notice"><%= notice %></p>
        </div>
      </div>
  <% end %>

  <div class="panel panel-default">
    <div class="panel-heading text-center">
      <h1>Task</h1>
    </div>
    <div class="panel-body">
      <div class="container">
        <div class="row">
          <p>
            <strong>Content:</strong>
            <%= raw(@task.content_html) %>
          </p>
        </div>
        <div class="row">
          <p>
            <strong>State:</strong>
            <%=  @task.state %>
          </p>
        </div>
        <div class="row">
          <%= link_to 'Edit', edit_task_path(@task), class: 'btn btn-primary' %>
          <%= link_to 'Back', tasks_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
</div>